/** \file
 *  This C++ header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : HLSL.g
 *     -                            On : 2012-06-14 16:58:03
 *     -                for the parser : HLSLParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C++ language generator and runtime by Gokulakannan Somasundaram ( heavy lifting from C Run-time by Jim Idle )
 *
 *
 * The parser 
HLSLParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Gokulakannan Somasundaram. 
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_HLSLParser_H
#define _HLSLParser_H
/* =============================================================================
 * Standard antlr3 C++ runtime definitions
 */
#include    <antlr3.hpp>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */


    #include "HLSLLexer.hpp"
    #include "HLSLParserListener.h"
    #include <iostream>
	#include <string>
   
    struct Parameter
    {
		std::string
			Type,
			Name,
			Semantic;
	};




#ifdef	WIN32
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */


typedef HLSLParserTraits HLSLParserImplTraits;


struct HLSLParser_texture_type_return : public HLSLParserImplTraits::RuleReturnValueType
{
public:
	typedef HLSLParserImplTraits::RuleReturnValueType BaseType;

    
    HLSLParser_texture_type_return()
    {
    }

    HLSLParser_texture_type_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    HLSLParser_texture_type_return( const HLSLParser_texture_type_return& n )
    : BaseType(n)
    {
    }

    HLSLParser_texture_type_return&
    operator=( const HLSLParser_texture_type_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};





struct HLSLParser_type_return : public HLSLParserImplTraits::RuleReturnValueType
{
public:
	typedef HLSLParserImplTraits::RuleReturnValueType BaseType;

    
    HLSLParser_type_return()
    {
    }

    HLSLParser_type_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    HLSLParser_type_return( const HLSLParser_type_return& n )
    : BaseType(n)
    {
    }

    HLSLParser_type_return&
    operator=( const HLSLParser_type_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};





struct HLSLParser_semantic_return : public HLSLParserImplTraits::RuleReturnValueType
{
public:
	typedef HLSLParserImplTraits::RuleReturnValueType BaseType;

    
    HLSLParser_semantic_return()
    {
    }

    HLSLParser_semantic_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    HLSLParser_semantic_return( const HLSLParser_semantic_return& n )
    : BaseType(n)
    {
    }

    HLSLParser_semantic_return&
    operator=( const HLSLParser_semantic_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};





struct HLSLParser_exp_return : public HLSLParserImplTraits::RuleReturnValueType
{
public:
	typedef HLSLParserImplTraits::RuleReturnValueType BaseType;

    
    HLSLParser_exp_return()
    {
    }

    HLSLParser_exp_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    HLSLParser_exp_return( const HLSLParser_exp_return& n )
    : BaseType(n)
    {
    }

    HLSLParser_exp_return&
    operator=( const HLSLParser_exp_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};






class HLSLParserTokens
{
public:
	/** Symbolic definitions of all the tokens that the 
parser
 will work with.
	 * \{
	 *
	 * Antlr will define EOF, but we can't use that as it it is too common in
	 * in C header files and that would be confusing. There is no way to filter this out at the moment
	 * so we just undef it here for now. That isn't the value we get back from C recognizers
	 * anyway. We are looking for ANTLR_TOKEN_EOF.
	 */
	enum Tokens 
	{
		EOF_TOKEN = HLSLParserImplTraits::CommonTokenType::TOKEN_EOF
		, T__16 = 16 
		, T__17 = 17 
		, T__18 = 18 
		, T__19 = 19 
		, T__20 = 20 
		, T__21 = 21 
		, T__22 = 22 
		, T__23 = 23 
		, T__24 = 24 
		, T__25 = 25 
		, T__26 = 26 
		, T__27 = 27 
		, T__28 = 28 
		, T__29 = 29 
		, T__30 = 30 
		, T__31 = 31 
		, T__32 = 32 
		, T__33 = 33 
		, T__34 = 34 
		, T__35 = 35 
		, T__36 = 36 
		, T__37 = 37 
		, T__38 = 38 
		, T__39 = 39 
		, T__40 = 40 
		, T__41 = 41 
		, T__42 = 42 
		, T__43 = 43 
		, T__44 = 44 
		, COMMENT = 4 
		, ESC_SEQ = 5 
		, EXPONENT = 6 
		, FLOAT = 7 
		, HEX_DIGIT = 8 
		, ID = 9 
		, INT = 10 
		, LEFT_CURLY = 11 
		, OCTAL_ESC = 12 
		, RIGHT_CURLY = 13 
		, STRING = 14 
		, WS = 15 
	};

};

/** Context tracking structure for 
HLSLParser

 */
class HLSLParser : public 
HLSLParserImplTraits::BaseParserType
, public HLSLParserTokens
{
public:
	typedef HLSLParserImplTraits ImplTraits;
	typedef HLSLParser ComponentType;
	typedef ComponentType::StreamType StreamType;
	typedef 
HLSLParserImplTraits::BaseParserType
 BaseType;
	typedef ImplTraits::RecognizerSharedStateType<StreamType> RecognizerSharedStateType;
	typedef StreamType InputType;
	static const bool IsFiltered = false;


private:	
public:
    HLSLParser(InputType* instream);
    HLSLParser(InputType* instream, RecognizerSharedStateType* state);

    void init(InputType* instream  );

     
     void
     translation_unit (); 
     
     void
     global_declaration (); 
     
     void
     technique (); 
     
     void
     pass (); 
     
     void
     vertex_shader_definition (); 
     
     void
     pixel_shader_definition (); 
     
     void
     type_definition (); 
     
     void
     variable_declaration (); 
     
     void
     sampler (); 
     
     void
     sampler_type (); 
     
     void
     sampler_parameter (); 
     
     void
     number_type (); 
     
     HLSLParser_texture_type_return
     texture_type (); 
     
     HLSLParser_type_return
     type (); 
     
     void
     field_declaration (); 
     
     HLSLParser_semantic_return
     semantic (); 
     
     void
     function (); 
     
     Parameter
     parameter_declaration (); 
     
     void
     statement (); 
     
     HLSLParser_exp_return
     exp (); 
     
     void
     variable (); 
     
     void
     function_call (); 
     
     void
     constructor (); 
     
     void
     number (); 
    // Delegated rules

    const char *    getGrammarFileName();
    void            reset();
    ~HLSLParser();


        HLSLParserListener
            * Listener;

};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//

/* End of token definitions for HLSLParser
 * =============================================================================
 */
/** } */


#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
